// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11UwNTtLzu0JlfPVKdQYQJ9NIVBMk6rg',
    appId: '1:210679891391:web:c69d532efffd7557078d0a',
    messagingSenderId: '210679891391',
    projectId: 'kombinv1',
    authDomain: 'kombinv1.firebaseapp.com',
    storageBucket: 'kombinv1.firebasestorage.app',
    measurementId: 'G-6FJVWG0NX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmkTeBi9omR9ZnpPwkrVDRW9Q1n3A8QNo',
    appId: '1:210679891391:android:8cf650ad7dba9fc0078d0a',
    messagingSenderId: '210679891391',
    projectId: 'kombinv1',
    storageBucket: 'kombinv1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMQ3s3OXdq-ZawSZ8uF_S5ymcdySXqe-k',
    appId: '1:210679891391:ios:455f92f12db39260078d0a',
    messagingSenderId: '210679891391',
    projectId: 'kombinv1',
    storageBucket: 'kombinv1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMQ3s3OXdq-ZawSZ8uF_S5ymcdySXqe-k',
    appId: '1:210679891391:ios:3c00c609b7536e8b078d0a',
    messagingSenderId: '210679891391',
    projectId: 'kombinv1',
    storageBucket: 'kombinv1.firebasestorage.app',
    iosBundleId: 'com.bglabs.luvia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC11UwNTtLzu0JlfPVKdQYQJ9NIVBMk6rg',
    appId: '1:210679891391:web:c69d532efffd7557078d0a',
    messagingSenderId: '210679891391',
    projectId: 'kombinv1',
    authDomain: 'kombinv1.firebaseapp.com',
    storageBucket: 'kombinv1.firebasestorage.app',
    measurementId: 'G-6FJVWG0NX9',
  );

}